name: "Generate GraphQL Docs"

on:
  push:
    branches: [ main2 ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: yarn install
    - name: Build docs
      run: yarn run build-docs
    - name: Deploy docs
      run: |
        git config --local user.name 'github-actions[bot]'
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
        git checkout -t -B docs
        git add public/
        git commit -m "Update docs: $GITHUB_SHA"
        git push
